name: Build documentation

on:
  push:
    branches:
      - main
      - doc-builder*
      - v*-release

jobs:
  build:
    uses: huggingface/doc-builder/.github/workflows/build_main_documentation.yml@main
    with:
      commit_sha: ${{ github.sha }}
      package: bitsandbytes
      repo_owner: TimDettmers
      custom_container: huggingface/transformers-doc-builder
    secrets:
      hf_token: ${{ secrets.HUGGINGFACE_PUSH }}
